LAB04-ED1/Models/ErrorViewModel.cs
using System;

namespace LAB04_ED1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LAB04-ED1/Controllers/HomeController.cs
using LAB04_ED1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LAB04_ED1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LAB04-ED1/Controllers/PriorityQueueController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClassLibrary;
using LAB04_ED1.Helpers;


namespace LAB04_ED1.Controllers
{
    public class PriorityQueueController : Controller
    {
        public static Func<Patient, int> PriorityCalculator = (patient) =>
        {
            int priority = 0;
            if (patient.Sex == "Male")
                priority += 3;
            else
                priority += 5;

            if (patient.Age >= 70)
                priority += 10;
            else if (patient.Age >= 50 && patient.Age <= 69)
                priority += 8;
            else if (patient.Age >= 18 && patient.Age <= 49)
                priority += 3;
            else if (patient.Age >= 6 && patient.Age <= 17)
                priority += 5;
            else if (patient.Age >= 0 && patient.Age <= 5)
                priority += 8;

            switch (patient.Specialization)
            {
                case "Internal traumatology":
                    priority += 3;
                    break;
                case "Exposed traumatology":
                    priority += 8;
                    break;
                case "Gynecology":
                    priority += 5;
                    break;
                case "Cardiology":
                    priority += 10;
                    break;
                case "Pneumology":
                    priority += 8;
                    break;
            }

            if (patient.EntryMethod == "Ambulance")
                priority += 5;
            else
                priority += 3;

            return priority;

        };







        // GET: PriorityQueueController
        public ActionResult Index()
        {
            Data.Instance.OutputPatientQueue = Data.Instance.PatientQueue.deepCopy();
            Data.Instance.OutputPatientQueue.swapNodes = Data.Instance.PatientQueue.swapNodes;
            Data.Instance.OutputPatientQueue.PriorityComparer = Data.Instance.PatientQueue.PriorityComparer;
            
            return View(Data.Instance.OutputPatientQueue.GetNodeList(Data.Instance.OutputPatientQueue.Root));  
        }

       
        public IActionResult Peek()
        {
            if (Data.Instance.PatientQueue.IsEmpty())
                return View();
            else
            {
                List<Patient> aux = new List<Patient>();
                aux.Add(Data.Instance.PatientQueue.Peek().Record);
                return View(aux);
            }
                
        }

        // GET: PriorityQueueController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PriorityQueueController/Create
        public ActionResult Create()
        {
            return View(new Patient());
        }

        // POST: PriorityQueueController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Patient patient = new Patient
                {
                  
                    Names = collection["Names"],
                    LastNames = collection["LastNames"],
                    BirthDate = Convert.ToDateTime(collection["BirthDate"]),
                    Age = (DateTime.Now.Year - Convert.ToDateTime(collection["BirthDate"]).Year),
                    Sex = collection["Sex"],
                    Specialization = collection["Specialization"],
                    EntryMethod = collection["EntryMethod"],
                    EntryDate = Convert.ToDateTime(collection["EntryDate"]),
                    EntryTime = collection["EntryTime"]
                };

                patient.Priority = PriorityCalculator(patient);

                Node<Patient> NewNode = new Node<Patient>(patient);
                NewNode.IsNull = 0;
                Data.Instance.PatientQueue.Root = Data.Instance.PatientQueue.Add(Data.Instance.PatientQueue.Root, NewNode);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Remove()
        {
            Data.Instance.PatientQueue.Remove();
           

            return RedirectToAction(nameof(Index));
        }


        // GET: PriorityQueueController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PriorityQueueController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
               
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PriorityQueueController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PriorityQueueController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LAB04-ED1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LAB04-ED1/Views/PriorityQueue/Create.cshtml
@model ClassLibrary.Patient

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Patient</h4>
<hr />

@{
    string day = DateTime.Now.Day.ToString();
    string month = DateTime.Now.Month.ToString();
    if (DateTime.Now.Day < 10) 
        day = day.Insert(0, "0");
    if (DateTime.Now.Month < 10)
        month = month.Insert(0, "0");

    string Today = $"{DateTime.Now.Year.ToString()}-{month}-{day}";

    string CurrentTime = DateTime.Now.ToLongTimeString();

}


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Names" class="control-label"></label>
                <input asp-for="Names" class="form-control" />
                <span asp-validation-for="Names" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastNames" class="control-label"></label>
                <input asp-for="LastNames" class="form-control" />
                <span asp-validation-for="LastNames" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Sex"></label>
                <select asp-for="Sex" class="form-control bg-dark text-white">
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input type="date" min="1900-01-01" value="@Today" max="@Today" asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Specialization"></label>
                <select asp-for="Specialization" class="form-control bg-dark text-white">
                    <option value="Internal traumatology" selected>Internal traumatology</option>
                    <option value="Exposed traumatology">Exposed traumatology</option>
                    <option value="Gynecology">Gynecology</option>
                    <option value="Cardiology">Cardiology</option>
                    <option value="Pneumology">Pneumology</option>
                </select>
                <span asp-validation-for="Specialization" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EntryMethod"></label>
                <select asp-for="EntryMethod" class="form-control bg-dark text-white">
                    <option value="Ambulance" selected>Ambulance</option>
                    <option value="Assisted">Assisted</option>
                </select>
                <span asp-validation-for="EntryMethod" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EntryDate" class="control-label"></label>
                <input type="date" max="@Today" value="@Today" asp-for="EntryDate" class="form-control" />
                <span asp-validation-for="EntryDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EntryTime" class="control-label"></label>
                <input asp-for="EntryTime" readonly value="@CurrentTime" class="form-control" />
                <span asp-validation-for="EntryTime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LAB04-ED1/Views/PriorityQueue/Index.cshtml
@model IEnumerable<ClassLibrary.Patient>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>


<form asp-controller="PriorityQueue" asp-action="Peek" method="post" enctype="multipart/form-data">
    <button class="btn-light btn-outline-info" value="buttonClick">Current patient</button>
</form><br />

 


<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Names)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastNames)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sex)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Specialization)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EntryMethod)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EntryDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Priority)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @{ if (Model != null)
           {
                @foreach (var item in Model)
                 {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Names)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastNames)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Sex)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Age)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Specialization)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EntryMethod)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EntryDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Priority)
                        </td>
                    </tr>
                 }
           }}
    </tbody>
</table>

LAB04-ED1/Views/PriorityQueue/Peek.cshtml
@model IEnumerable<ClassLibrary.Patient>

@{
    ViewData["Title"] = "Peek";
}

<h1>Current patient</h1>


<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.Names)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastNames)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sex)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Specialization)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EntryMethod)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EntryDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Priority)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{ if (Model != null)
                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Names)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastNames)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Sex)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Age)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Specialization)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EntryMethod)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EntryDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Priority)
                        </td>
                        <td>
                            @Html.ActionLink("Finish consultation", "Remove")
                        </td>


                    </tr>



                }

        }


        <div>
            <a asp-action="Index">Back to List</a>
        </div>

    </tbody>
</table>

LAB04-ED1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LAB04_ED1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LAB04_ED1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PriorityQueue" asp-action="Index">Queue</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LAB04_ED1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>